#!/usr/bin/env sh

files="src/**/*.js"
pnpm run format "$files"
format_status=$?
pnpm run lint "$files"
lint_status=$?

if [ $format_status -ne 0 ] || [ $lint_status -ne 0 ]; then
  echo "Pre-commit checks failed. Please fix the issues before committing."
  exit 1
fi

git add "$files"
